### PR TITLE
Prevent setting a public upstream when creating a private repo.

### LINKED ISSUE #1854: `hub create -p` can unexpectedly set the upstream to a public repo
When I use `hub create -p` (specifying to create a private repo), there should be no situation where hub sets the remote to a public repository. This behaviour makes it trivially easy to accidently push private code to a new public repository.

In the event that a repo of the same name already exists, and is public, `hub` will detect the existing repo and set the upstream. *It gives no clear indication that the upstream registered is not a private repository*.

For example, the following results in a public repo being set as `origin` as the result of a command to create a private repository:
```
test ❯ git init
Initialized empty Git repository in /workspace/env/test/.git/
test (master) ❯ hub create
Updating origin
https://github.com/nrmitchi/test
test (master) ❯ rm -rf .git
test ❯ git init
Initialized empty Git repository in /workspace/env/test/.git/
test (master) ❯ hub create -p
Existing repository detected. Updating git remote
Updating origin
https://github.com/nrmitchi/test
```

While there is a message that an existing repository was found, it seems to me that `hub` should exit with a failure if the named repository already exists, but doesn't match the privacy settings that were specified.

### PR DESCRIPTION
**Pull request by nrmitchi**
Fixes #1854

### CODE REVIEW

File: commands/create.go [hunk 1]
```diff
@@ -110,7 +110,18 @@ func create(command *Command, args *Args) {
 	gh := github.NewClient(project.Host)
 
 	if gh.IsRepositoryExist(project) {
-		ui.Errorln("Existing repository detected. Updating git remote")
+
+		repo, err := gh.Repository(project)
```
Comment (mislav) [inline commands/create.go]: This queries `gh.Repository()` info again after `gh.IsRepositoryExist()` already queried it (but only returned a boolean). If you need to query whether a repository exist *and* access its info, it would be best to call `gh.Repository()` once initially and base all subsequent checks on that result.

File: commands/create.go [hunk 2]
```diff
@@ -110,7 +110,18 @@ func create(command *Command, args *Args) {
...
+		if err != nil {
+			utils.Check(err)
+		}
+
+		if !repo.Private && flagCreatePrivate {
+			err = fmt.Errorf("Existing public repository detected. git remote not updated")
```
Comment (mislav) [inline commands/create.go]: I would like to see a clearer error message, like:

```go
fmt.Errorf("Repository `%s' already exists and is public", repo.FullName)
```

Comment (nrmitchi) [reply commands/create.go]: I wasn't quite sure about the messaging, I'll go with your suggestion

File: commands/create.go (hunk 1 above)
Comment (nrmitchi) [reply commands/create.go]: Good catch. Seeing that the `IsRepositoryExist` function is not used elsewhere, do you have objections to removing it?

File: commands/create.go [hunk 3]
```diff
@@ -109,8 +109,18 @@ func create(command *Command, args *Args) {
 	project := github.NewProject(owner, newRepoName, host.Host)
 	gh := github.NewClient(project.Host)
 
-	if gh.IsRepositoryExist(project) {
-		ui.Errorln("Existing repository detected. Updating git remote")
+	repo, err := gh.Repository(project)
+	if err != nil {
+		utils.Check(err)
```
Comment (mislav) [inline commands/create.go]: I think this breaks current CI checks. Keep in mind that `err` will be present if the repo doesn't exist. This whole conditional can go away.

File: commands/create.go [hunk 4]
```diff
@@ -109,8 +109,18 @@ func create(command *Command, args *Args) {
...
+	}
+
+	if repo != nil {
```
Comment (mislav) [inline commands/create.go]: This can be `err == nil`. In that case you can be sure that `repo` is non-nil. No other checks are necessary

File: commands/create.go (hunk 3 above)
Comment (nrmitchi) [reply commands/create.go]: Yupp, this took me a bit to figure out why all the tests were breaking. It did occur to me that we don't currently differentiate between a "the repo doesn't exist" error, and a _real_ error. In that situation a duplicate error wouldn't be created (assuming the github api handles the conflict properly), however it could be dealt with better in hub itself.

It's not really a concern here though, and is outside the scope of what I'm trying to accomplish with this PR

**Comment by mislav** [comment]
Thank  you!! ✨

**Comment by nrmitchi** [comment]
No problem! Thanks for getting this merged in so quickly
