### PR TITLE
Extract logic of printing out to console

### LINKED ISSUE #801: One Command test outputs text to stdout
[This specific commands test](https://github.com/github/hub/blob/1409606542e9140324d8b9c113bdb095355f8b4b/commands/commands_test.go#L133-141) outputs `usage: foo` to stdout. This output is only visible if some other test in "commands" package fails.

Ideally, tests should output nothing to stdout, as all their output should be captured and asserted.

### PR DESCRIPTION
**Pull request by jingweno**
Introduce a `console` package which encapsulates logic of printing out
to console. This provides flexibility of discarding output in tests.
It also allows us to unify format of printing to console (if we want to).

This fixes #801.

### CODE REVIEW

File: commands/commands_test.go [hunk 1]
```diff
@@ -1,11 +1,16 @@
...
 
 import (
+	"io/ioutil"
 	"testing"
 
 	"github.com/github/hub/Godeps/_workspace/src/github.com/bmizerany/assert"
 )
 
+func init() {
+	UI = ui{Stdout: ioutil.Discard, Stderr: ioutil.Discard}
```
Comment (jingweno) [inline commands/commands_test.go]: This is the code muting the print out to console in tests

File: commands/commands_test.go [hunk 2]
```diff
@@ -1,11 +1,19 @@
...
+	"io/ioutil"
+	"os"
 	"testing"
 
 	"github.com/github/hub/Godeps/_workspace/src/github.com/bmizerany/assert"
+	"github.com/github/hub/console"
 )
 
+func TestMain(m *testing.M) {
+	console.Default = console.Console{Stdout: ioutil.Discard, Stderr: ioutil.Discard}
```
Comment (jingweno) [inline commands/commands_test.go]: I did some refactoring again. This is the new code to mute the print out to console in tests

Comment (mislav) [inline commands/commands_test.go]: Since TestMain affects all tests everywhere, should we put it in a file where it's more apparent that this is a global setting?

Also, shouldn't we capture the output instead of discard it?

**Comment by mislav** [comment]
It's a good start, but "console" might be a slight misnomer because a unix executable doesn't know and shouldn't care where its output is going or who's going to read it.

Is there an option to keep our `fmt.Println` and similar but somehow capture and redirect all standard output in tests to a string so we can inspect it? This is trivial in Ruby.

File: commands/commands_test.go (hunk 2 above)
Comment (jingweno) [inline commands/commands_test.go]: > Since TestMain affects all tests everywhere

This `TestMain` will only affect the commands package. We'd need to put it into a test file in the rest of packages if we want this to be global.

> Also, shouldn't we capture the output instead of discard it?

I'm not aware of any test that asserts the output yet. For [`TestCommandCall`](https://github.com/github/hub/blob/master/commands/commands_test.go#L130) mentioned in #801, we're checking the the function is called and the arguments are correctly passed in.

**Comment by jingweno** [comment]
> "console" might be a slight misnomer because a unix executable doesn't know and shouldn't care where its output is going

Any suggestion? I'm thinking something as generic as `ui.Infoln`. or `log.Infoln`.

> Is there an option to keep our fmt.Println and similar but somehow capture and redirect all standard output in tests to a string so we can inspect it?

Yup, `Console` expects `Stdout` and `Stderr` to be `io.Writer`, which is an interface to all writer, including [bytes of string](http://golang.org/pkg/bytes/#Buffer), so:

```go
var b bytes.Buffer
console.Default = Console{Stdout: &b, Stderr: &b}
// do something with b
```

**Comment by jingweno** [comment]
@mislav Any more feedback here?

**Comment by mislav** [comment]
I think "UI" is a good name, because it's an interface with whoever is using the tool from the outside. I'd also like to keep the `Println` and `Printf` names.

How about:

* `ui.Println`
* `ui.Printf`
* `ui.Errorln`
* `ui.Errorf`

**Comment by jingweno** [comment]
> I think "UI" is a good name, because it's an interface with whoever is using the tool from the outside.

I've extracted `UI` into [an interface](https://github.com/github/hub/blob/fix_test_output/ui/ui.go) and `Console` as an implementation.

> I'd also like to keep the Println and Printf names.

After a second thought, I agree `Println` and `Printf` are better since they are the same as the ones from `fmt`. Fixed with `--amend`.

**Comment by jingweno** [comment]
Merging since all comments are addressed.
